---
learning_rate: 0.00001 # The initial learning rate for the model.
seed: 0 # Random seed.
epochs: 150 # Number of epochs to train.
hidden: 240 # Number of hidden units.
dropout: 0.5 # Dropout rate (1 - keep probability).
batch_size: 1 # Number of graphs in a batch.
poolratio: 0.8

embed_dim: 2 # The dimension of graph embeddings.